language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - <your email address>
    on_success: always
    on_failure: always
branches:
  only:
    - development
before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://duskabyss777.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development

